name = "VoronoiCells"
uuid = "e3e34ffb-84e9-5012-9490-92c94d0c60a4"
authors = ["Robert Dahl Jacobsen <git@dahl-jacobsen.dk>"]
version = "0.2.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
VoronoiDelaunay = "72f80fcb-8c52-57d9-aff0-40c1a3526986"

[compat]
Deldir = "1.3"
GeometryBasics = "0.3.5"
RecipesBase = "1.1"
VoronoiDelaunay = "0.4.0"
julia = "1.5"

[extras]
Deldir = "64db5801-a3ae-51a7-b7d2-a0a5f0813e47"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Deldir", "Random"]
